---
- name: playbook to start, stop, and restart a service
  hosts: all
  remote_user: khatwar
  become: true
  tasks:
    - name: start a service
      ansible.builtin.service:
        name: apache2
        state: started

    - name: restart a service
      ansible.builtin.service:
        name: apache2
        state: restarted

    - name: stop a service
      ansible.builtin.service:
        name: apache2
        state: stopped