---
- name: Playbook that creates a directory structure with custom permissions
  hosts: all
  remote_user: khatwar
  become: true
  tasks:
    - name: Create a directory structure with custom permissions
      ansible.builtin.file:
        path: "{{ item.path }}"
        state: directory
        owner: "{{ item.owner }}"
        group: "{{ item.owner }}"
        mode: "{{ item.mode }}"
      loop:
      - {path: '/home/khatwar/ds1', owner: 'khatwar', mode: '0755'}
      - {path: '/home/khatwar/ds2', owner: 'khatwar', mode: '0755'}
      - {path: '/home/khatwar/ds3', owner: 'khatwar', mode: '0755'}
      - {path: '/home/khatwar/ds1/dds2', owner: 'khatwar', mode: '0755'}
      - {path: '/home/khatwar/ds1/dds3', owner: 'khatwar', mode: '0755'}
      - {path: '/home/khatwar/ds2/dds1', owner: 'khatwar', mode: '0755'}
      - {path: '/home/khatwar/ds3/ddds4/dddsss5', owner: 'khatwar', mode: '0755'}
