---
- name: playbook to install multiple packages
  hosts:
  remote_user: khatwar
  become: true
  tasks:
    - name: install multiple packages
      ansible.builtin.apt:
        name:
          - git
          - apache2
          - wget
        state: present
        update_cache: yes