---
- name: Playbook that installs Docker and starts a container using docker_container
  hosts: all
  remote_user: khatwar
  become: true
  tasks:
    - name: Install Docker
      ansible.builtin.apt:
        name: docker.io
        state: present

    - name: Add user to Docker group
      ansible.builtin.user:
        name: khatwar
        groups: docker
        append: yes
    
    - name: Start a container using docker_container
      community.docker.docker_container:
        name: apache_container
        image: httpd:latest
        state: present
        published_ports:
          - "80:80"
