---
- name: playbook to create a user named deploy with a specific SSH key
  hosts: all
  remote_user: khatwar
  become: true

  vars:
    ssh_key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAICHQBZoDzD7PlO29cYvpOb5DhlK1doYc3A83n3s/tbMX root@ip-172-31-10-77"

  tasks:
    - name: create user
      ansible.builtin.user:
        name: hatwar
        state: present
        create_home: yes
        shell: /bin/bash

    - name: make .shh directory
      ansible.builtin.file:
        path: /home/hatwar/.ssh
        state: directory
        owner: hatwar
        group: hatwar
        mode: '0700'

    - name: copy SSH key
      ansible.builtin.copy:
        content: "{{ ssh_key }}"
        dest: /home/hatwar/.ssh/authorized_keys
        owner: hatwar
        group: hatwar
        mode: '0600'